[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[project]
name = "llama-index-workflows-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{name = "Adrian Lyjak", email = "adrianlyjak@gmail.com"}]
requires-python = ">=3.9"
dependencies = [
  "llama-index-workflows>=2.12.0,<3.0.0",
  "llama-index-workflows-client>=0.1.0,<0.2.0",
  "starlette>=0.39.0",
  "uvicorn>=0.32.0"
]

[project.scripts]
llama-index-workflows-server = "llama_index_workflows_server:main"

[tool.uv.sources]
llama-index-workflows = {workspace = true}
llama-index-workflows-client = {workspace = true}
