[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "pre-commit>=4.3.0",
  "pytest>=8.4.2",
  "pytest-asyncio>=1.0.0",
  "pytest-cov>=7.0.0",
  "pytest-timeout>=2.4.0",
  "pytest-xdist>=3.8.0"
]

[project]
name = "llama-index-utils-workflow"
version = "0.8.0"
description = "llama-index utils for workflows"
readme = "README.md"
authors = [{name = "Adrian Lyjak", email = "adrianlyjak@gmail.com"}]
requires-python = ">=3.9"
dependencies = [
  "llama-index-core>=0.14,<0.15.0",
  "llama-index-workflows>=2.13.0,<3.0.0",
  "pyvis>=0.3.2"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "module"
testpaths = ["tests"]
addopts = "-nauto --timeout=10"

[tool.uv.build-backend]
module-name = "llama_index.utils.workflow"
