[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.4.2", "pytest-asyncio>=1.0.0", "pytest-cov>=6.1.1"]

[project]
name = "llama-index-utils-workflow"
version = "0.5.0"
description = "llama-index utils for workflows"
readme = "README.md"
authors = [{name = "Adrian Lyjak", email = "adrianlyjak@gmail.com"}]
requires-python = ">=3.9"
dependencies = [
  "llama-index-core>=0.14,<0.15.0",
  "llama-index-workflows>=2.9.0,<3.0.0",
  "pyvis>=0.3.2"
]

[tool.hatch.build.targets.sdist]
only-include = ["src/llama_index"]

[tool.hatch.build.targets.wheel]
packages = ["src/llama_index"]
