name: Unit Testing

on:
  pull_request:
  push:
    branches:
      - main

env:
  # Which Python from the matrix will be used to run the coverage check
  COV_PYTHON_VERSION: 3.14

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        package:
          [
            llama-index-workflows,
            llama-index-utils-workflow,
            workflows-dev,
            llama-index-integration-tests,
          ]
        exclude:
          - package: workflows-dev
            python-version: "3.9"
          - package: workflows-dev
            python-version: "3.10"
          - package: workflows-dev
            python-version: "3.11"
          - package: workflows-dev
            python-version: "3.12"
          - package: workflows-dev
            python-version: "3.13"
        include:
          - package: llama-index-workflows
            package_dir: packages/llama-index-workflows
          - package: llama-index-utils-workflow
            package_dir: packages/llama-index-utils-workflow
          - package: workflows-dev
            package_dir: packages/workflows-dev
          - package: llama-index-integration-tests
            package_dir: packages/llama-index-integration-tests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Run tests
        if: matrix.python-version != env.COV_PYTHON_VERSION
        run: uv run --all-extras --directory ${{ matrix.package_dir }} -- pytest

      - name: Run tests with coverage
        if: matrix.python-version == env.COV_PYTHON_VERSION
        run: uv run --all-extras --directory ${{ matrix.package_dir }} -- pytest --cov=src --cov-report=xml

      - name: Report Coveralls
        if: matrix.python-version == env.COV_PYTHON_VERSION
        uses: coverallsapp/github-action@v2
        with:
          file: ${{ matrix.package_dir }}/coverage.xml
          flag-name: ${{ matrix.package }}
          parallel: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  coveralls-finish:
    needs: test
    runs-on: ubuntu-latest
    if: github.repository == 'run-llama/workflows-py'
    steps:
      - name: Finalize Coveralls parallel jobs
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
